server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://notification-db:5432/notification_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: mailhog        # point at your MailHog container
    port: 1025
    # no auth/TLS required for MailHog
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    queue: notification-queue

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

# your application’s own queue setting
notification:
  queue-name: notification-queue
