server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  # Security config (empty if not used, can be omitted)
  security:
  # oauth2:
  #   resourceserver:
  #     # No JWT block for now

  # RabbitMQ config
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  # Database config (!!! Check DB name: should match your event DB)
  datasource:
    url: jdbc:postgresql://db:5432/eventdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate config
  jpa:
    hibernate:
      ddl-auto: update    # <--- change to 'update' for persistence after confirming everything works
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:ChangeMeJWTSecretKey}

logging:
  level:
    root: INFO
    com.example.eventmanager: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.oauth2.server.resource.authentication: TRACE
    org.springframework.security.oauth2.server.resource.web: TRACE
