server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: jj/d7SSI1Q5X8Cyznz1wNECeWnIVUsYgMnEGp5DemaGmyD1P0TfLXeFjjsZLEVLMCkeDia/5qh5dMWQUpnWv8g
          authorities-claim-name: roles   # <-- ADD THIS LINE!

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://db:5432/eventdb   # <-- confirm the DB name!
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.example.eventmanager: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.oauth2.server.resource.authentication: TRACE
    org.springframework.security.oauth2.server.resource.web: TRACE
