server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://USER-AUTH-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: AuthenticationFilter
        - id: event-manager
          uri: lb://EVENT-MANAGER-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - name: AuthenticationFilter

jwt:
  secret: ${JWT_SECRET:changeThisSecret}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
